source "https://rubygems.org"
gem 'disqus-for-jekyll'
gem 'jekyll', '~> 3.9.0'
gem 'jekyll-paginate'
gem 'jekyll-gist'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-git_metadata'
gem 'kramdown', '~> 2.3'
gem 'kramdown-parser-gfm', '~> 1.1'